"""first migration

Revision ID: 21fa646ef1bf
Revises: 
Create Date: 2024-09-04 15:59:34.266355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fa646ef1bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typeIdentifiedData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('databaseScan',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('host', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_scan', sa.DateTime(), nullable=True),
    sa.Column('lates_version', sa.Integer(), nullable=True),
    sa.Column('user_create_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_create_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('scanDomain',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('database_id', sa.CHAR(length=36), nullable=False),
    sa.Column('version_scan', sa.Integer(), nullable=False),
    sa.Column('date_scan', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databaseScan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('scanTables',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('domain_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['scanDomain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('scanDetailTables',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('table_id', sa.CHAR(length=36), nullable=False),
    sa.Column('nameColumn', sa.String(length=200), nullable=False),
    sa.Column('typeIdentified_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['scanTables.id'], ),
    sa.ForeignKeyConstraint(['typeIdentified_id'], ['typeIdentifiedData.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanDetailTables')
    op.drop_table('scanTables')
    op.drop_table('scanDomain')
    op.drop_table('databaseScan')
    op.drop_table('users')
    op.drop_table('typeIdentifiedData')
    # ### end Alembic commands ###
