services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME?Variable not set}
      - DB_SERVER=${DB_SERVER?Variable not set}
      - DB_PORT=${DB_PORT?Variable not set}
      - DB_USER=${DB_USER?Variable not set}
      - DB_PASSWORD=${DB_PASSWORD?Variable not set}
      - DB_NAME=${DB_NAME?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - ALGORITHM=${ALGORITHM?Variable not set}
      - ENCRYPTKEY=${ENCRYPTKEY?Variable not set}

    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME?Variable not set}
      - MYSQL_USER=${DB_USER?Variable not set}
      - MYSQL_PASSWORD=${DB_PASSWORD?Variable not set}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD?Variable not set}
    volumes:
      - db-data:/var/lib/mysql

  dbPrueba:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME_PRUEBA?Variable not set}
      - MYSQL_USER=${DB_USER_PRUEBA?Variable not set}
      - MYSQL_PASSWORD=${DB_PASSWORD?Variable not set}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD?Variable not set}

volumes:
  db-data:
